### ISSUE TITLE
Fails to build without -DNDEBUG e.g., via -DCMAKE_BUILD_TYPE=Unknown

### ISSUE THREAD

**Issue by jbeich** [ReinUsesLisp/sirit#19]
Regressed by 22cc6f6c1bec. [Found](https://github.com/ReinUsesLisp/sirit/files/3953087/yuzu-qt5-s20191211.log) via Yuzu.

Clang 9.0.0 reports:
```c++
src/op.cpp:85:21: fatal error: implicit conversion turns string literal into bool: 'const char [21]' to 'bool' [-Wstring-conversion]
            assert(!"Invalid literal type");
                   ~^~~~~~~~~~~~~~~~~~~~~~
/usr/include/assert.h:56:21: note: expanded from macro 'assert'
#define assert(e)       ((e) ? (void)0 : __assert(__func__, __FILE__, \
                          ^
src/op.cpp:115:56: fatal error: declaration shadows a field of 'Sirit::Op' [-Wshadow]
    assert(std::all_of(ids.begin(), ids.end(), [](auto id) { return id; }));
                                                       ^
src/./op.h:56:24: note: previous declaration is here
    std::optional<u32> id;
                       ^
2 errors generated.
```
GCC 9.1.0 reports:
```c++
In file included from /usr/include/c++/cassert:44,
                 from src/op.cpp:8:
src/op.cpp: In lambda function:
src/op.cpp:115:58: error: declaration of 'id' shadows a member of 'Sirit::Op' [-Werror=shadow]
  115 |     assert(std::all_of(ids.begin(), ids.end(), [](auto id) { return id; }));
      |                                                          ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```

**Comment by jbeich** [comment]
If Clang error is fixed then it sees the same error as GCC:
```c++
src/op.cpp:115:56: fatal error: declaration shadows a field of 'Sirit::Op' [-Wshadow]
    assert(std::all_of(ids.begin(), ids.end(), [](auto id) { return id; }));
                                                       ^
src/./op.h:56:24: note: previous declaration is here
    std::optional<u32> id;
                       ^
```

**Comment by ReinUsesLisp** [comment]
Pushed two commits to silence those errors. Let me know if you find new ones.

**Comment by jbeich** [comment]
Thanks. Builds fine now with Clang and GCC. Also, [confirmed](https://github.com/ReinUsesLisp/sirit/files/3955638/yuzu-qt5-s20191211.log) via Yuzu.
